### ISSUE TITLE
Федосеев А.А.

### ISSUE THREAD

**Issue by faaswdepkhab** [drclaws/dr.analyzer#2]
Здравствуй, Александр!

Немножко нетрадиционный способ способ использования issues, но другого способа связаться с тобой у меня нет. Надо срочно связаться с Сегренёвым Ильёй. Может быть у тебя есть его контакты? Если не трудно, скинь на [убрал на всякий]

**Comment by drclaws** [comment]
Только сейчас увидел. Не знаю как с актуальностью, но все равно отправил ему сообщение с этим адресом. На будущее если надо будет связаться со мной, то лучше смс на телефон, который чуть позже отправлю на этот адрес
